# Generated by Django 5.0.6 on 2024-06-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDevice',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ad_brand_name', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('ad_model_no', models.CharField(max_length=20, verbose_name='Model Number')),
                ('ad_mac_address', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('ad_device_status', models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], max_length=50, verbose_name='Device Status')),
                ('ad_assign_status', models.CharField(choices=[('Pending', 'Pending'), ('Assign', 'Assign')], max_length=50, verbose_name='ASSIGN STATUS')),
                ('ad_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name_plural': 'Assign Device',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('city_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('country_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captain_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('c_name', models.CharField(max_length=100, verbose_name='Name')),
                ('c_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('c_contact_no', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('c_address', models.CharField(max_length=100, verbose_name='Address')),
                ('c_documents', models.JSONField(default=dict, null=True, verbose_name='Documents')),
                ('c_license_no', models.CharField(max_length=50, verbose_name='License Number')),
                ('c_license_image', models.JSONField(verbose_name='License Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('Assign_Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.assigndevice', verbose_name='Assign Device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Captain',
            },
        ),
        migrations.CreateModel(
            name='CaptainTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Check In')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check Out')),
                ('total_hours', models.DurationField(blank=True, null=True, verbose_name='Total Hours')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Close', 'Close')], default='Pending', max_length=10, verbose_name='Status')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.captain', verbose_name='Captain')),
            ],
            options={
                'verbose_name_plural': 'Captain Trips',
            },
        ),
        migrations.CreateModel(
            name='EarnPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.captain', verbose_name='Captain')),
            ],
            options={
                'verbose_name_plural': 'Earn Points',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('state_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'State',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='captain',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='TwoFactorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_secret', models.CharField(max_length=255, verbose_name='OTP Secret')),
                ('session_identifier', models.UUIDField(blank=True, null=True, verbose_name='Session Identifier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('ud_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('contact_no', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cl_contact_person_name', models.CharField(max_length=100, verbose_name='Name')),
                ('cl_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cl_contact_no', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('cl_secondary_contact_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Secondary Contact Number')),
                ('cl_address', models.CharField(max_length=200, verbose_name='Address')),
                ('cl_gst_no', models.CharField(max_length=50, unique=True, verbose_name='GST Number')),
                ('cl_firm_name', models.CharField(max_length=100, verbose_name='Firm Name')),
                ('cl_firm_address', models.CharField(max_length=200, verbose_name='Firm Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='captain',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cm_geo_fencing', models.TextField(verbose_name='Geo Fencing')),
                ('cm_ad_video_file', models.JSONField(verbose_name='Ad Video File')),
                ('cm_no_of_repetition', models.IntegerField(verbose_name='No of repetition')),
                ('cm_start_date', models.DateField(verbose_name='Start Date')),
                ('cm_tenure', models.IntegerField(verbose_name='Tenure')),
                ('cm_end_date', models.DateField(editable=False, verbose_name='End Date')),
                ('cm_amount', models.IntegerField(verbose_name='Amount')),
                ('cm_status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], editable=False, max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Campaign',
            },
        ),
        migrations.AddField(
            model_name='assigndevice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='VehicleLicenseInformation',
            fields=[
                ('vi_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('vi_vehicle_no', models.CharField(max_length=50, verbose_name='Vehicle Number')),
                ('vi_vehicle_image', models.JSONField(verbose_name='Vehicle Image')),
                ('vi_rc_book_image', models.JSONField(verbose_name='RC Book Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.userdetails', verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Vehicle License Information',
            },
        ),
        migrations.AddField(
            model_name='captain',
            name='VehicleLicense_Information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.vehiclelicenseinformation', verbose_name='Vehicle License'),
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Viewed At')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.campaign', verbose_name='Campaign')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Captain')),
            ],
            options={
                'verbose_name_plural': 'Video Views',
            },
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'state_name'), name='unique_state_name'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('country_name',), name='unique_country_name'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('cl_gst_no',), name='unique_gst_no'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'city_name'), name='unique_city_name'),
        ),
        migrations.AddConstraint(
            model_name='assigndevice',
            constraint=models.UniqueConstraint(fields=('ad_brand_name', 'ad_model_no', 'ad_mac_address'), name='unique_device'),
        ),
        migrations.AlterUniqueTogether(
            name='captain',
            unique_together={('c_email', 'c_license_no')},
        ),
    ]
