# Generated by Django 5.0.3 on 2024-06-04 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=50)),
                ('a_latitude', models.FloatField()),
                ('a_longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='twofactordata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCharge',
            fields=[
                ('cc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_range', models.CharField(max_length=10)),
                ('cc_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cc_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyInformation',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ai_name', models.CharField(max_length=100)),
                ('ai_Email', models.EmailField(max_length=254, unique=True)),
                ('ai_contact_number', models.IntegerField()),
                ('ai_second_contact_number', models.IntegerField()),
                ('ai_address_1', models.CharField(max_length=100)),
                ('ai_address_2', models.CharField(max_length=100)),
                ('ai_pincode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('ci_id', models.AutoField(primary_key=True, serialize=False)),
                ('ci_name', models.CharField(max_length=100)),
                ('ci_email', models.EmailField(max_length=254, unique=True)),
                ('ci_contact_number', models.IntegerField()),
                ('ci_second_contact_number', models.IntegerField()),
                ('ci_address_1', models.CharField(max_length=100)),
                ('ci_address_2', models.CharField(max_length=100)),
                ('ci_pincode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ci_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.agencyinformation')),
                ('ci_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_video_files', models.JSONField()),
                ('c_number_of_repetition', models.IntegerField()),
                ('c_start_date', models.DateField()),
                ('c_tenure', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('c_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.area')),
                ('c_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.clientinformation')),
            ],
        ),
        migrations.CreateModel(
            name='DriverBasicInformation',
            fields=[
                ('dbi_id', models.AutoField(primary_key=True, serialize=False)),
                ('dbi_name', models.CharField(max_length=100)),
                ('dbi_email', models.EmailField(max_length=254, unique=True)),
                ('dbi_mobile_number', models.IntegerField()),
                ('dbi_address_1', models.CharField(max_length=100)),
                ('dbi_address_2', models.CharField(max_length=100)),
                ('dbi_pincode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dbi_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city')),
                ('dbi_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_brand_name', models.CharField(max_length=50)),
                ('d_model_number', models.CharField(max_length=50)),
                ('d_mac_address', models.CharField(max_length=50)),
                ('d_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('d_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='BankingInformation',
            fields=[
                ('bki_id', models.AutoField(primary_key=True, serialize=False)),
                ('bki_name', models.CharField(max_length=50)),
                ('bki_account_holder_name', models.CharField(max_length=100)),
                ('bki_account_number', models.IntegerField()),
                ('bki_ifsc_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bki_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AutoKYC',
            fields=[
                ('ak_id', models.AutoField(primary_key=True, serialize=False)),
                ('ak_aadhar_card', models.JSONField()),
                ('ak_kyc_token', models.CharField(max_length=100)),
                ('ak_thumb_print', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ak_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ManualKYC',
            fields=[
                ('mk_id', models.AutoField(primary_key=True, serialize=False)),
                ('mk_aadhar_card', models.JSONField()),
                ('mk_pan_card', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mk_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutConfiguration',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_range', models.CharField(max_length=50)),
                ('pc_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pc_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='driverbasicinformation',
            name='dbi_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='ci_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state'),
        ),
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('bi_id', models.AutoField(primary_key=True, serialize=False)),
                ('bi_name', models.CharField(max_length=100)),
                ('bi_email', models.EmailField(max_length=254, unique=True)),
                ('bi_connect_number', models.IntegerField()),
                ('bi_second_connect_number', models.IntegerField()),
                ('bi_address_1', models.CharField(max_length=100)),
                ('bi_address_2', models.CharField(max_length=100)),
                ('bi_pincode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bi_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city')),
                ('bi_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.clientinformation')),
                ('bi_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state')),
            ],
        ),
        migrations.AddField(
            model_name='agencyinformation',
            name='ai_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state'),
        ),
        migrations.CreateModel(
            name='VehicleLicenseInformation',
            fields=[
                ('vli_id', models.AutoField(primary_key=True, serialize=False)),
                ('vi_number', models.CharField(max_length=10)),
                ('vi_photo', models.JSONField()),
                ('vi_rc_photo', models.JSONField()),
                ('li_number', models.CharField(max_length=50)),
                ('li_photo', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vli_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation')),
            ],
        ),
    ]
