# Generated by Django 5.0.6 on 2024-06-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0002_campaign_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='last_checked',
        ),
    ]
