# Generated by Django 5.0.3 on 2024-06-04 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0002_area_alter_twofactordata_id_city_campaigncharge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State'},
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_Email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_address_1',
            field=models.CharField(max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_address_2',
            field=models.CharField(max_length=100, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_contact_number',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_pincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_second_contact_number',
            field=models.IntegerField(verbose_name='Second Contact Number'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='area',
            name='a_latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='area',
            name='a_longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='area',
            name='a_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='autokyc',
            name='ak_aadhar_card',
            field=models.JSONField(verbose_name='Aadhar Card'),
        ),
        migrations.AlterField(
            model_name='autokyc',
            name='ak_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='autokyc',
            name='ak_kyc_token',
            field=models.CharField(max_length=100, verbose_name='KYC Token'),
        ),
        migrations.AlterField(
            model_name='autokyc',
            name='ak_thumb_print',
            field=models.JSONField(verbose_name='Thumb Print'),
        ),
        migrations.AlterField(
            model_name='autokyc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='bankinginformation',
            name='bki_account_holder_name',
            field=models.CharField(max_length=100, verbose_name='Account Holder Name'),
        ),
        migrations.AlterField(
            model_name='bankinginformation',
            name='bki_account_number',
            field=models.IntegerField(verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bankinginformation',
            name='bki_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='bankinginformation',
            name='bki_ifsc_code',
            field=models.CharField(max_length=20, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='bankinginformation',
            name='bki_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bankinginformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_address_1',
            field=models.CharField(max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_address_2',
            field=models.CharField(max_length=100, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.clientinformation', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_connect_number',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_pincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_second_connect_number',
            field=models.IntegerField(verbose_name='Second Contact Number'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='c_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='c_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.clientinformation', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='c_number_of_repetition',
            field=models.IntegerField(verbose_name='Number of Repetition'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='c_start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='c_tenure',
            field=models.DateField(verbose_name='Tenure'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='c_video_files',
            field=models.JSONField(verbose_name='Video Files'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='campaigncharge',
            name='cc_amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='campaigncharge',
            name='cc_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='campaigncharge',
            name='cc_range',
            field=models.CharField(max_length=10, verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='campaigncharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_address_1',
            field=models.CharField(max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_address_2',
            field=models.CharField(max_length=100, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.agencyinformation', verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_contact_number',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_pincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_second_contact_number',
            field=models.IntegerField(verbose_name='Second Contact Number'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_brand_name',
            field=models.CharField(max_length=50, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_mac_address',
            field=models.CharField(max_length=50, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_model_number',
            field=models.CharField(max_length=50, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_address_1',
            field=models.CharField(max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_address_2',
            field=models.CharField(max_length=100, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_mobile_number',
            field=models.IntegerField(verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_pincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='manualkyc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='manualkyc',
            name='mk_aadhar_card',
            field=models.JSONField(verbose_name='Aadhar Card'),
        ),
        migrations.AlterField(
            model_name='manualkyc',
            name='mk_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='manualkyc',
            name='mk_pan_card',
            field=models.JSONField(verbose_name='Pan Card'),
        ),
        migrations.AlterField(
            model_name='payoutconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='payoutconfiguration',
            name='pc_amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payoutconfiguration',
            name='pc_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='payoutconfiguration',
            name='pc_range',
            field=models.CharField(max_length=50, verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='li_number',
            field=models.CharField(max_length=50, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='li_photo',
            field=models.JSONField(verbose_name='License Photo'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_number',
            field=models.CharField(max_length=10, verbose_name='Vehicle Number'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_photo',
            field=models.JSONField(verbose_name='Vehicle Photo'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_rc_photo',
            field=models.JSONField(verbose_name='Vehicle RC Photo'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vli_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver'),
        ),
    ]
