# Generated by Django 5.0.3 on 2024-06-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0003_alter_state_options_alter_agencyinformation_ai_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
    ]
