# Generated by Django 5.0.3 on 2024-06-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0004_alter_state_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_address_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_address_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_address_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.agencyinformation', verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_address_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Address 2'),
        ),
    ]
