# Generated by Django 5.0.6 on 2024-06-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0004_userdetails_last_retrieval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='last_retrieval',
        ),
    ]
