# Generated by Django 5.0.3 on 2024-06-04 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0006_remove_clientinformation_ci_agency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=50, verbose_name='Name')),
                ('a_latitude', models.FloatField(verbose_name='Latitude')),
                ('a_longitude', models.FloatField(verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCharge',
            fields=[
                ('cc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_range', models.CharField(max_length=10, verbose_name='Range')),
                ('cc_amount', models.IntegerField(verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('cc_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyInformation',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ai_name', models.CharField(max_length=100, verbose_name='Name')),
                ('ai_Email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ai_contact_number', models.IntegerField(verbose_name='Contact Number')),
                ('ai_second_contact_number', models.IntegerField(null=True, verbose_name='Second Contact Number')),
                ('ai_address_1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('ai_address_2', models.CharField(max_length=100, null=True, verbose_name='Address 2')),
                ('ai_pincode', models.IntegerField(verbose_name='Pincode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ai_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('ci_id', models.AutoField(primary_key=True, serialize=False)),
                ('ci_name', models.CharField(max_length=100, verbose_name='Name')),
                ('ci_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ci_contact_number', models.IntegerField(verbose_name='Contact Number')),
                ('ci_second_contact_number', models.IntegerField(null=True, verbose_name='Second Contact Number')),
                ('ci_address_1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('ci_address_2', models.CharField(max_length=100, null=True, verbose_name='Address 2')),
                ('ci_pincode', models.IntegerField(verbose_name='Pincode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ci_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.agencyinformation', verbose_name='Agency')),
                ('ci_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_video_files', models.JSONField(verbose_name='Video Files')),
                ('c_number_of_repetition', models.IntegerField(verbose_name='Number of Repetition')),
                ('c_start_date', models.DateField(verbose_name='Start Date')),
                ('c_tenure', models.DateField(verbose_name='Tenure')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('c_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.area', verbose_name='Area')),
                ('c_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.clientinformation', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='DriverBasicInformation',
            fields=[
                ('dbi_id', models.AutoField(primary_key=True, serialize=False)),
                ('dbi_name', models.CharField(max_length=100, verbose_name='Name')),
                ('dbi_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('dbi_mobile_number', models.IntegerField(verbose_name='Mobile Number')),
                ('dbi_address_1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('dbi_address_2', models.CharField(max_length=100, null=True, verbose_name='Address 2')),
                ('dbi_pincode', models.IntegerField(verbose_name='Pincode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('dbi_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
                ('dbi_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_brand_name', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('d_model_number', models.CharField(max_length=50, verbose_name='Model Number')),
                ('d_mac_address', models.CharField(max_length=50, verbose_name='MAC Address')),
                ('d_status', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('d_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver')),
            ],
        ),
        migrations.CreateModel(
            name='BankingInformation',
            fields=[
                ('bki_id', models.AutoField(primary_key=True, serialize=False)),
                ('bki_name', models.CharField(max_length=50, verbose_name='Name')),
                ('bki_account_holder_name', models.CharField(max_length=100, verbose_name='Account Holder Name')),
                ('bki_account_number', models.IntegerField(verbose_name='Account Number')),
                ('bki_ifsc_code', models.CharField(max_length=20, verbose_name='IFSC Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bki_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver')),
            ],
        ),
        migrations.CreateModel(
            name='AutoKYC',
            fields=[
                ('ak_id', models.AutoField(primary_key=True, serialize=False)),
                ('ak_aadhar_card', models.JSONField(verbose_name='Aadhar Card')),
                ('ak_kyc_token', models.CharField(max_length=100, verbose_name='KYC Token')),
                ('ak_thumb_print', models.JSONField(verbose_name='Thumb Print')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ak_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver')),
            ],
        ),
        migrations.CreateModel(
            name='ManualKYC',
            fields=[
                ('mk_id', models.AutoField(primary_key=True, serialize=False)),
                ('mk_aadhar_card', models.JSONField(verbose_name='Aadhar Card')),
                ('mk_pan_card', models.JSONField(verbose_name='Pan Card')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('mk_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutConfiguration',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_range', models.CharField(max_length=50, verbose_name='Range')),
                ('pc_amount', models.IntegerField(verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pc_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.AddField(
            model_name='driverbasicinformation',
            name='dbi_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='ci_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('bi_id', models.AutoField(primary_key=True, serialize=False)),
                ('bi_name', models.CharField(max_length=100, verbose_name='Name')),
                ('bi_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('bi_connect_number', models.IntegerField(verbose_name='Contact Number')),
                ('bi_second_connect_number', models.IntegerField(null=True, verbose_name='Second Contact Number')),
                ('bi_address_1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('bi_address_2', models.CharField(max_length=100, null=True, verbose_name='Address 2')),
                ('bi_pincode', models.IntegerField(verbose_name='Pincode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bi_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City')),
                ('bi_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.clientinformation', verbose_name='Client')),
                ('bi_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='agencyinformation',
            name='ai_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='VehicleLicenseInformation',
            fields=[
                ('vli_id', models.AutoField(primary_key=True, serialize=False)),
                ('vi_number', models.CharField(max_length=10, verbose_name='Vehicle Number')),
                ('vi_photo', models.JSONField(verbose_name='Vehicle Photo')),
                ('vi_rc_photo', models.JSONField(verbose_name='Vehicle RC Photo')),
                ('li_number', models.CharField(max_length=50, verbose_name='License Number')),
                ('li_photo', models.JSONField(verbose_name='License Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('vli_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.driverbasicinformation', verbose_name='Driver')),
            ],
        ),
    ]
