# Generated by Django 5.0.3 on 2024-06-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0007_area_city_campaigncharge_agencyinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_address_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='agencyinformation',
            name='ai_second_contact_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Second Contact Number'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_address_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='bi_second_connect_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Second Contact Number'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_address_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.agencyinformation', verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ci_second_contact_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Second Contact Number'),
        ),
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_address_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
    ]
