# Generated by Django 5.0.3 on 2024-06-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0008_alter_agencyinformation_ai_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverbasicinformation',
            name='dbi_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_photo',
            field=models.FileField(upload_to='Vehicle Photos/'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_rc_photo',
            field=models.FileField(upload_to='Vehicle RC Photos/'),
        ),
    ]
