# Generated by Django 5.0.3 on 2024-06-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0009_alter_driverbasicinformation_dbi_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='li_photo',
            field=models.FileField(upload_to='License Photo/', verbose_name='License Photo'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_photo',
            field=models.FileField(upload_to='Vehicle Photos/', verbose_name='Vehicle Photo'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_rc_photo',
            field=models.FileField(upload_to='Vehicle RC Photos/', verbose_name='Vehicle RC Photo'),
        ),
    ]
