# Generated by Django 5.0.3 on 2024-06-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0012_alter_vehiclelicenseinformation_li_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='li_photo',
            field=models.ImageField(upload_to='License Photo/', verbose_name='License Photo'),
        ),
    ]
