# Generated by Django 5.0.3 on 2024-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0013_alter_vehiclelicenseinformation_li_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_number',
            field=models.CharField(max_length=20, verbose_name='Vehicle Number'),
        ),
    ]
