# Generated by Django 5.0.3 on 2024-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0014_alter_vehiclelicenseinformation_vi_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vli_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
