# Generated by Django 5.0.3 on 2024-06-06 10:13

import django.db.models.deletion
import django_admin_geomap
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0017_location_lat_location_lon_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUuid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name='WithQuotas',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='p_app.location')),
            ],
            bases=('p_app.location',),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
