# Generated by Django 5.0.3 on 2024-06-06 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0021_remove_clientinformation_ci_agency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('ud_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('contact_no', models.IntegerField(verbose_name='Contact Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('c_name', models.CharField(max_length=100, verbose_name='Name')),
                ('c_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('c_contact_no', models.IntegerField(verbose_name='Contact Number')),
                ('c_address', models.CharField(max_length=100, verbose_name='Address')),
                ('c_documents', models.JSONField(verbose_name='Documents')),
                ('c_license_no', models.CharField(max_length=50, verbose_name='License Number')),
                ('c_license_image', models.JSONField(verbose_name='License Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='AssignDevice',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ad_brand_name', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('ad_model_no', models.CharField(max_length=20, verbose_name='Model Number')),
                ('ad_mac_address', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('ad_device_status', models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], max_length=50)),
                ('ad_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ad_created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ad_captain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.captain', verbose_name='Captain')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('city_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.AddField(
            model_name='captain',
            name='c_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='City'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cl_contact_person_name', models.CharField(max_length=100, verbose_name='Name')),
                ('cl_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cl_contact_no', models.IntegerField(verbose_name='Contact Number')),
                ('cl_secondary_contact_no', models.IntegerField(verbose_name='Secondary Contact Number')),
                ('cl_address', models.CharField(max_length=200, verbose_name='Address')),
                ('cl_gst_no', models.CharField(max_length=50, verbose_name='GST Number')),
                ('cl_firm_name', models.CharField(max_length=100, verbose_name='Firm Name')),
                ('cl_firm_address', models.CharField(max_length=200, verbose_name='Firm Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('cl_firm_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='Firm City')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cm_geo_fencing', models.CharField(max_length=100, verbose_name='Geo Fencing')),
                ('cm_ad_video_file', models.JSONField(verbose_name='Ad Video File')),
                ('cm_no_of_repetition', models.IntegerField(verbose_name='No of repetition')),
                ('cm_start_date', models.DateField(verbose_name='Start Date')),
                ('cm_tenure', models.IntegerField(verbose_name='Tenure')),
                ('cm_end_date', models.DateField(verbose_name='End Date')),
                ('cm_amount', models.IntegerField(verbose_name='Amount')),
                ('cm_status', models.BooleanField(verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('cm_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('country_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('state_name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='cl_firm_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='Firm State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='captain',
            name='c_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='VehicleLicenseInformation',
            fields=[
                ('vi_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('vi_vehicle_no', models.CharField(max_length=50, verbose_name='Vehicle Number')),
                ('vi_vehicle_image', models.JSONField(verbose_name='Vehicle Image')),
                ('vi_rc_book_image', models.JSONField(verbose_name='RC Book Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('vi_captain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.captain', verbose_name='Captain')),
            ],
        ),
    ]
