# Generated by Django 5.0.3 on 2024-06-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0022_userdetails_captain_assigndevice_city_captain_c_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationUuid',
        ),
        migrations.DeleteModel(
            name='WithQuotas',
        ),
    ]
