# Generated by Django 5.0.3 on 2024-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0026_alter_client_cl_secondary_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='c_documents',
            field=models.JSONField(default=dict, null=True, verbose_name='Documents'),
        ),
    ]
