# Generated by Django 5.0.3 on 2024-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0027_alter_captain_c_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='c_documents',
            field=models.FileField(null=True, upload_to='media/document/', verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_license_image',
            field=models.FileField(upload_to='media/licenses/', verbose_name='License Image'),
        ),
    ]
