# Generated by Django 5.0.3 on 2024-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0028_alter_captain_c_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='c_documents',
            field=models.JSONField(default=dict, null=True, verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_license_image',
            field=models.JSONField(verbose_name='License Image'),
        ),
    ]
