# Generated by Django 5.0.3 on 2024-06-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0034_alter_campaign_cm_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
    ]
