# Generated by Django 5.0.3 on 2024-06-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0035_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
    ]
