# Generated by Django 5.0.3 on 2024-06-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0036_alter_country_options_alter_country_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
    ]
