# Generated by Django 5.0.3 on 2024-06-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0039_alter_assigndevice_ad_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigndevice',
            options={'verbose_name_plural': 'Assign Device'},
        ),
    ]
