# Generated by Django 5.0.3 on 2024-06-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0040_alter_assigndevice_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name_plural': 'Campaign'},
        ),
        migrations.AlterModelOptions(
            name='captain',
            options={'verbose_name_plural': 'Captain'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'State'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
        migrations.AlterModelOptions(
            name='vehiclelicenseinformation',
            options={'verbose_name_plural': 'Vehicle License Information'},
        ),
    ]
