# Generated by Django 5.0.3 on 2024-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0041_delete_location_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='c_contact_no',
            field=models.IntegerField(max_length=10, verbose_name='Contact Number'),
        ),
    ]
