# Generated by Django 5.0.3 on 2024-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0044_alter_vehiclelicenseinformation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cm_geo_fencing',
            field=models.CharField(max_length=1000, verbose_name='Geo Fencing'),
        ),
    ]
