# Generated by Django 5.0.3 on 2024-06-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0049_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contact_no',
            field=models.CharField(max_length=10, unique=True, verbose_name='Contact Number'),
        ),
    ]
