# Generated by Django 5.0.3 on 2024-06-17 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0050_alter_userdetails_contact_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_assign_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assign', 'Assign')], default='Pending', max_length=50, null=True, verbose_name='ASSIGN STATUS'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_brand_name',
            field=models.CharField(max_length=50, verbose_name='BRAND NAME'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_device_status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], max_length=50, verbose_name='DEVICE STATUS'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_mac_address',
            field=models.CharField(max_length=50, verbose_name='MAC ADDRESS'),
        ),
        migrations.AlterField(
            model_name='assigndevice',
            name='ad_model_no',
            field=models.CharField(max_length=20, verbose_name='MODEL NUMBER'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_ad_video_file',
            field=models.JSONField(verbose_name='AD VIDEO FILE'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_amount',
            field=models.IntegerField(verbose_name='AMOUNT'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.client', verbose_name='CLIENT'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_end_date',
            field=models.DateField(editable=False, verbose_name='END DATE'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_geo_fencing',
            field=models.CharField(max_length=1000, verbose_name='GEO FENCING'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_no_of_repetition',
            field=models.IntegerField(verbose_name='NO OF REPETITION'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_start_date',
            field=models.DateField(verbose_name='START DATE'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], editable=False, max_length=50, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cm_tenure',
            field=models.IntegerField(verbose_name='TENURE'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_address',
            field=models.CharField(max_length=100, verbose_name='ADDRESS'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_assign_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.assigndevice', verbose_name='ASSIGN DEVICE'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='CITY'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_contact_no',
            field=models.IntegerField(verbose_name='CONTACT NUMBER'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_documents',
            field=models.JSONField(default=dict, null=True, verbose_name='DOCUMENTS'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_license_image',
            field=models.JSONField(verbose_name='LICENSE IMAGE'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_license_no',
            field=models.CharField(max_length=50, verbose_name='LICENSE NUMBER'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_name',
            field=models.CharField(max_length=100, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='c_vehicle_license_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='p_app.vehiclelicenseinformation', verbose_name='VEHICLE LICENSE'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=50, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_address',
            field=models.CharField(max_length=200, verbose_name='ADDRESS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_contact_no',
            field=models.IntegerField(verbose_name='CONTACT NUMBER'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_contact_person_name',
            field=models.CharField(max_length=100, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_firm_address',
            field=models.CharField(max_length=200, verbose_name='FIRM ADDRESS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_firm_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.city', verbose_name='FIRM CITY'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_firm_name',
            field=models.CharField(max_length=100, verbose_name='FIRM NAME'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_firm_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.state', verbose_name='FIRM STATE'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_gst_no',
            field=models.CharField(max_length=50, verbose_name='GST NUMBER'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_secondary_contact_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='SECONDARY CONTACT NUMBER '),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_app.country', verbose_name='COUNTRY'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=50, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.CharField(max_length=200, verbose_name='ADDRESS'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact_no',
            field=models.CharField(max_length=10, unique=True, verbose_name='CONTACT NUMBER'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ud_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CREATED BY'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_rc_book_image',
            field=models.JSONField(verbose_name='RC BOOK IMAGE'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_vehicle_image',
            field=models.JSONField(verbose_name='VEHICLE IMAGE'),
        ),
        migrations.AlterField(
            model_name='vehiclelicenseinformation',
            name='vi_vehicle_no',
            field=models.CharField(max_length=50, verbose_name='VEHICLE NUMBER'),
        ),
    ]
