# Generated by Django 5.0.3 on 2024-06-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0051_alter_assigndevice_ad_assign_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captain',
            name='c_assign_device',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cm_client',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='c_city',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='c_state',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='c_vehicle_license_information',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cl_firm_city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cl_firm_state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclelicenseinformation',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AssignDevice',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Captain',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='VehicleLicenseInformation',
        ),
    ]
