# Generated by Django 5.0.6 on 2024-06-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0005_remove_userdetails_last_retrieval'),
        ('p_app', '0055_captain_user_alter_assigndevice_created_by_and_more'),
    ]

    operations = [
    ]
