# Generated by Django 5.0.6 on 2024-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0056_merge_20240625_1747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assigndevice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assigndevice',
            constraint=models.UniqueConstraint(fields=('ad_brand_name', 'ad_model_no', 'ad_mac_address'), name='unique_device'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'city_name'), name='unique_city_name'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('cl_gst_no',), name='unique_gst_no'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'state_name'), name='unique_state_name'),
        ),
    ]
