from django.urls import path
from . import views

urlpatterns = [
    path("admin/register/", views.register, name="register"),
    path('admin/logout/', views.custom_logout_view, name='admin-logout'),
    path("confirm-2fa/", views.AdminConfirmTwoFactorAuthView.as_view(), name="confirm-2fa"),
    path("view_qrcode/<int:user_id>", views.view_qrcode, name="view_qrcode"),
    path('regenerate_qr_code/<int:user_id>/', views.regenerate_qr_code_view, name='regenerate_qr_code'),
    path('admin/captains/add/', views.custom_captain_create, name='custom_captain_create'),
    path('admin/captains/<int:pk>/change/', views.custom_captain_change, name='custom_captain_change'),
    path('close_captain', views.close_captain, name='close_captain'),
    path('admin/campaign/add/', views.custom_campaign_create, name='custom_campaign_create'),
    path('admin/campaign/<int:pk>/change/', views.custom_campaign_change, name='custom_campaign_change'),
    path('close_campaign/', views.close_campaign, name='close_campaign'),
    path('admin/client/add/', views.custom_client_create, name='custom_client_create'),
    path('admin/client/<int:pk>/change/', views.custom_client_change, name='custom_client_change'),
    path('close_client', views.close_client, name='close_client'),
    path('admin/city/add/', views.custom_city_create, name='custom_city_create'),
    path('admin/city/<int:pk>/change', views.custom_city_change, name='custom_city_change'),
    path('close_city', views.close_city, name='close_city'),
    path('admin/state/add/', views.custom_state_create, name='custom_state_create'),
    path('admin/state/<int:pk>/change/', views.custom_state_change, name='custom_state_change'),
    path('close_state/', views.close_state, name='close_state'),
    path('admin/vehiclelicenseinformation/add/', views.custom_vehicle_license_information_create,
         name='custom_vehicle_license_information_create'),
    path('admin/vehiclelicenseinformation/<int:pk>/change/', views.custom_vehicle_license_information_change,
         name='custom_vehicle_license_information_change'),
    path('close_vehiclelicenseinformation/', views.close_vehiclelicenseinformation,
         name='close_vehiclelicenseinformation'),
    path('admin/assign_device/add/', views.custom_assign_device_create, name='custom_assign_device_create'),
    path('admin/assign_device/<int:pk>/change/', views.custom_assign_device_change, name='custom_assign_device_change'),
    path('close_assign_device/', views.close_assign_device, name='close_assign_device'),
    path('admin/country/add', views.custom_country_create, name='custom_country_create'),
    path('admin/country/<int:pk>/change', views.custom_country_change, name='custom_country_change'),
    path('close_country', views.close_country, name='close_country'),
    path('setting/', views.setting, name='setting'),
]
